language: node_js

sudo: false

env:
  - CXX=g++-4.8 XXHASH=1
  - XXHASH=0

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "0.12"
  - "4"
  - "5"

install:
  - sh .travis/install.sh

script:
  - npm run eslint
  - npm run jscs
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js